name: Erlang CI

on: [push]

jobs:

  build_and_test:

    runs-on: ubuntu-24.04

    name: OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        otp:
          - "28.0"
          - "29.0"
    steps:
    - uses: actions/checkout@v7.0.1
    - uses: erlef/setup-beam@v1.24.1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: 3.27.0
    - name: Compile
      run: make
    - name: Run elvis
      run: make elvis_rock
    - name: Run xref
      run: make xref
    - name: Run dialyzer
      run: make dialyze
    - name: Run common tests
      run: make ct


  release:
    if: github.ref == 'refs/heads/master' && startsWith(github.event.head_commit.message, 'no-release:') == false
    needs: build_and_test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        TAG: ${{ steps.tag_version.outputs.new_tag }}
        CHANGELOG: ${{ steps.tag_version.outputs.changelog }}
      run: |
        gh release create "$TAG" --title "Release $TAG" --notes "$CHANGELOG"
